name: RTAI CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v --tb=short
    
    - name: Test indicator pipeline
      run: |
        python test_indicators_real_data.py
    
    - name: Start server for health check
      run: |
        uvicorn rtai.api.server:app --port 8000 &
        sleep 10  # Give server time to start

    - name: WebSocket health check
      run: |
        python scripts/ws_health_check.py
        
    - name: Integration test complete pipeline
      run: |
        python test_complete_pipeline.py
    
    - name: Check for banned modules
      run: |
        if grep -r "import matplotlib\|from matplotlib" rtai/; then
          echo "❌ Found banned matplotlib imports"
          exit 1
        fi
        if grep -r "import mplfinance\|from mplfinance" rtai/; then
          echo "❌ Found banned mplfinance imports"
          exit 1
        fi
        echo "✅ No banned modules found"
